name: Sync Fork

on:
  schedule:
    - cron: '0 8 * * *' # Daily
  workflow_dispatch: # on button click

jobs:
  sync:
    if: github.repository_owner != 'libimobiledevice' # Only on forks
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: libimobiledevice
          base: master
          head: master
